swagger: '2.0'
info:
  title: SE2
  description: SE2 is a simple API allowing user to create exam and tasks.
  version: "8234aab51481d37a30757d925b7f4221a659427e"
host: se2-2018.herokuapp.com
schemes:
  - https
paths:
  /exams:
    x-summary: Questions Collection
    x-description: ''
    get:
      summary: List all exams
      responses:
        200:
          description: 'List'
          examples:
            application/json:
              - name: 'Exam name'
              - id: 25